#================================ Inputs =====================================
filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'
  fields:
    type: docker_filebeat_log
    # To set the environment use the field: environment
    environment: production
    #environment: no-production
    # To set the environment use the field: location
    location: Milan
    
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

- type: docker
  # Paths that should be crawled and fetched. Glob based paths.
  paths:
  - '/var/log/messages'
  json.message_key: log
  json.keys_under_root: true
  # Change to true to enable this prospector configuration.
  enabled: true
  encoding: utf-8
  include_lines: ['dockerd']
  fields:
    type: messages_filebeat_log
    # To set the environment use the field: environment
    environment: production
    # To set the environment use the field: location
    location: Milan

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
#  indices:
#    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["logstash:5044"]

