#================================ Inputs =====================================
filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'
  fields:
    type: docker_filebeat_log
    # To set the environment use the field: environment
    environment: production
    #environment: no-production
    # To set the environment use the field: location
    location: Milan
    
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true



#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.
#output.elasticsearch:
#  hosts: ["elasticsearch:9200"]
#  indices:
#    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["logstash:5044"]

